name: Build-Docker

on:
  push:
  create:
  page_build:
  workflow_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4

      - name: set up qemu
        uses: docker/setup-qemu-action@v1.2.0

      - name: set up buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          buildkitd-flags: --debug
          
      - name: login to docker hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
                
      - name: build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          push: true
          build-args: TAG=latest
          tags: dotwee/focalboard:latest
